composer.json, monorepo-builder.yaml, packages/config-class-presence/.gitattributes, packages/config-class-presence/.github/FUNDING.yaml, packages/config-class-presence/.gitignore, packages/config-class-presence/LICENSE, packages/config-class-presence/README.md, packages/config-class-presence/bin/config-class-presence, packages/config-class-presence/composer.json, packages/config-class-presence/config/config.yaml, packages/config-class-presence/src/Command/CheckCommand.php, packages/config-class-presence/src/Console/ConfigClassPresenceApplication.php, packages/config-class-presence/src/Finder/ConfigFinder.php, packages/config-class-presence/src/HttpKernel/ConfigClassPresenceKernel.php, packages/config-class-presence/src/Regex/NonExistingClassExtractor.php, packages/config-class-presence/src/ValueObject/Option.php, packages/diff-data-miner/bin/diff-data-miner, packages/fatal-error-scanner/bin/fatal-error-scanner
=> [ConfigClassPresence] Init

packages/config-transformer/packages/format-switcher/src/ConfigLoader.php, packages/config-transformer/packages/format-switcher/src/Converter/ConfigFormatConverter.php, packages/config-transformer/packages/format-switcher/src/Converter/YamlToPhpConverter.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/AbstractConfigFormatConverterTest.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureXmlToPhp/some.xml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/XmlToPhpTest.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/XmlToYamlTest.php, phpstan.neon, rector-ci.yaml
Ref:
- https://github.com/symfony/symfony/issues/37186
- https://github.com/symfony/maker-bundle/pull/604
- https://github.com/archeoprog/maker-bundle/blob/make-convert-services/src/Util/PhpServicesCreator.php
Huge thanks to @archeoprog for making the yaml to php dumper :clap:  :clap:  :clap:
=> [ConfigTransformer] Add Xml To PHP

packages/config-transformer/packages/clarifier/src/Command/ClarifyCommand.php, packages/config-transformer/packages/format-switcher/src/Converter/YamlToPhpConverter.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/ParametersPhpNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/PhpNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/ServicesPhpNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/SingleServicePhpNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/Printer/FluentMethodCallPrinter.php, packages/config-transformer/packages/format-switcher/src/ValueObject/VariableName.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureXmlToPhp/some.xml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/nested/some_config/autodiscovery.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/nested/some_config/defaults.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/nested/some_config/exclude.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/normal/simple_arguments.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/normal/some.yaml, packages/config-transformer/src/Naming/ClassNaming.php, rector-ci.yaml
=> [ConfigTransformer] various node-related improvements

packages/config-transformer/packages/format-switcher/config/config.yaml, packages/config-transformer/packages/format-switcher/src/Converter/YamlToPhpConverter.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/ArgsNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/CommonNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/ImportNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/Service/AliasNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/ServicesPhpNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/SingleServicePhpNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeTraverser/ImportFullyQualifiedNamesNodeTraverser.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeVisitor/ImportFullyQualifiedNamesNodeVisitor.php, packages/config-transformer/packages/format-switcher/src/PhpParser/Printer/FluentPhpConfigurationPrinter.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_alias.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_arguments.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_deprecation.yaml, phpstan.neon
=> [ConfigTransformer] Moving from string to nodes

packages/config-transformer/packages/format-switcher/src/Converter/YamlToPhpConverter.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/ArgsNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/ServicesPhpNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/SingleServicePhpNodeFactory.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/instanceof.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/reference.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_alias.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_arguments.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_calls.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_configurator.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_decoration.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_deprecation.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_factory.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_null_value.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_simple.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_tags.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/Source/ExistingClass.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/Source/FakeClass.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/Source/SecondFakeClass.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/Source/ThirdFakeClass.php
=> [ConfigTransformer] re-use node factories

packages/config-transformer/packages/format-switcher/src/Converter/YamlToPhpConverter.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/CommonNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/Printer/FluentPhpConfigurationPrinter.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureXmlToPhp/some.xml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/parameters.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_staging.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/nested/some_config/imports.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/nested/some_config/parameters.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/Source/MimeTypes.php
=> [ConfigTransformer] Move empty line management to printer

packages/class-presence/composer.json, packages/config-transformer/composer.json, packages/diff-data-miner/composer.json, packages/easy-ci/composer.json, packages/fatal-error-scanner/composer.json, packages/latte-to-twig/composer.json
"bin" in composer.json should be array of strings, not string.
See https://getcomposer.org/doc/articles/vendor-binaries.md#how-is-it-defined-
=> Fix invalid composer.json. Bin must be string

packages/config-transformer/packages/format-switcher/src/Converter/ServiceOptionsKeyYamlToPhpFactory/ArgumentsServiceOptionKeyYamlToPhpFactory.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/maker-bundle/services_arguments.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/normal/argument_nesting.yaml
=> [ConfigTransformer] Make named args per line with arg()

packages/config-transformer/packages/format-switcher/src/Configuration/Configuration.php, packages/config-transformer/packages/format-switcher/src/Converter/KeyYamlToPhpFactory/ImportsKeyYamlToPhpFactory.php, packages/config-transformer/packages/format-switcher/src/Guard/InputValidator.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/AbstractConfigFormatConverterTest.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/normal/import_suffix_change.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhpTest.php
=> [ConfigTransformer] Change imported file suffix from input to output format

packages/config-transformer/packages/feature-shifter/src/ValueObject/YamlKey.php, packages/config-transformer/packages/format-switcher/src/Converter/ServiceKeyYamlToPhpFactory/DefaultsServiceKeyYamlToPhpFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/Service/AutoBindNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/Service/ServicesPhpNodeFactory.php, packages/config-transformer/packages/format-switcher/src/ValueObject/SymfonyVersionFeature.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhp/normal/services_default_private.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/FixtureYamlToPhpSymfony33/normal/services_default_private.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhpTest.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhpTestSymfony33Test.php
=> [ConfigTransformer] make public(false) removed or to private(), depending on Symfony version

packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/ArgsNodeFactory.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_deprecation.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_factory.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/parameter_exception.yaml
=> [ConfigTransformer] Skip basic non-class params

composer.json, packages/config-transformer/packages/feature-shifter/src/ValueObject/YamlKey.php, packages/config-transformer/packages/format-switcher/src/Converter/ServiceOptionsKeyYamlToPhpFactory/TagsServiceOptionKeyYamlToPhpFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/ArgsNodeFactory.php, packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/Service/AutoBindNodeFactory.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/reference.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/maker-bundle/services_load_resources_simple.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/resource_with_tags.yaml
=> [ConfigTransformer] Add tags to resource

packages/class-presence/README.md, packages/config-transformer/README.md, packages/diff-data-miner/README.md, packages/easy-ci/README.md, packages/fatal-error-scanner/README.md, packages/latte-to-twig/README.md, packages/neon-to-yaml/README.md, packages/psr4-switcher/README.md, packages/symfony-route-usage/README.md, packages/template-checker/README.md, packages/vendor-patches/README.md, packages/zephir-to-php/README.md
refs https://github.com/migrify/migrify/issues/123
I tried to make this as generic as possible, so it can be copy/paste'd into the other components.
=> added notes about contribution/issue reporting

composer.json, ecs.php, packages/config-transformer/packages/format-switcher/src/Yaml/YamlCommentPreserver.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/comments/comment_after_item.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/comments/extra_comments_mix.yaml, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/comments/line_start_comment_in_list.yaml, packages/zephir-to-php/composer.json
=> [ConfigTransformer] fix comments in list after item

packages/config-transformer/packages/format-switcher/src/PhpParser/NodeFactory/ArgsNodeFactory.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/AbstractConfigFormatConverterTest.php, packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/twig_path.yaml
=> [ConfigTransformer] Fix keeping template path instead of ref

.github/workflows/rector_ci.yaml, .github/workflows/split_tests.yaml, packages/class-presence/src/Command/CheckCommand.php, packages/easy-ci/config/config.php, packages/easy-ci/src/Command/GenerateSonarProjectCommand.php, packages/easy-ci/src/Finder/SrcTestsDirectoriesFinder.php, packages/easy-ci/src/Sonar/PathsFactory.php, packages/easy-ci/src/ValueObject/SrcAndTestsDirectories.php, packages/easy-ci/tests/Finder/SrcTestsDirectoriesFinder/Fixture/nothing/bla/uff.txt, packages/easy-ci/tests/Finder/SrcTestsDirectoriesFinder/Fixture/only_test/tests/someFile.txt, packages/easy-ci/tests/Finder/SrcTestsDirectoriesFinder/SrcTestsDirectoriesFinderTest.php, sonar-project.properties
Closes #49 
```bash
vendor/bin/easy-ci generate-sonar-project
```
<br>
Closes #134
=> [EasyCI] Add GenerateSonarProjectCommand

packages/config-transformer/packages/format-switcher/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/parameter_env.yaml
=> [ConfigTransformer] add env() test case

packages/static-detector/src/Collector/StaticNodeCollector.php, packages/static-detector/src/Console/Command/DetectCommand.php, packages/static-detector/src/NodeVisitor/FilePathNodeVisitor.php, packages/static-detector/src/Output/StaticReportReporter.php, packages/static-detector/src/ValueObject/AttributeKey.php, packages/static-detector/src/ValueObject/StaticClassMethod.php, packages/static-detector/src/ValueObject/StaticClassMethodWithStaticCalls.php, packages/static-detector/src/ValueObject/StaticDetectorAttributeKey.php
=> [StaticDetector] simplify file line value

packages/config-transformer/README.md, packages/config-transformer/packages/format-switcher/src/Configuration/Configuration.php
```bash
vendor/bin/config-transformer switch-format ecs.yaml -i yaml
```
```bash
vendor/bin/config-transformer switch-format ecs.yaml
```
=> [ConfigTransformer] Autoresolve input file suffix, in case of 1 file

packages/template-checker/src/Analyzer/MissingClassesLatteAnalyzer.php, packages/template-checker/tests/Analyzer/MissingClassesLatteAnalyzer/Fixture/existing_class_instanceof.latte, packages/template-checker/tests/Analyzer/MissingClassesLatteAnalyzer/Fixture/existing_var_type.latte, packages/template-checker/tests/Analyzer/MissingClassesLatteAnalyzer/Fixture/missing_class_instanceof.latte, packages/template-checker/tests/Analyzer/MissingClassesLatteAnalyzer/Fixture/missing_classes.latte, packages/template-checker/tests/Analyzer/MissingClassesLatteAnalyzer/Fixture/missing_input.latte, packages/template-checker/tests/Analyzer/MissingClassesLatteAnalyzer/Fixture/missing_var_type.latte, packages/template-checker/tests/Analyzer/MissingClassesLatteAnalyzer/MissingClassesLatteAnalyzerTest.php
=> [TemplateChecker] Add instanceof + varType checks

packages/static-detector/composer.json
see https://github.com/migrify/static-detector/issues/1
=> removed circular dependency in composer

.travis.yml, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/normal/router_request_context_base_url.yaml, packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/YamlToPhpTest.php, packages/php-config-printer/src/NodeFactory/CommonNodeFactory.php
Fixes https://github.com/migrify/migrify/issues/198
=> [ConfigTransformer] Fix empty string to dir conversion

composer.json
Fixes https://github.com/composer/composer/issues/9382
=> composer: remove phalcon left over

packages/config-transformer/tests/Converter/ConfigFormatConverter/YamlToPhp/Fixture/routing/routes_with_extra_parameters.yaml, packages/php-config-printer/src/RoutingCaseConverter/PathRoutingCaseConverter.php
=> not all nested keys were added
